#include "..\..\includes\base.h"
#define PREFIX other
FNC_CFG_CL_START()
FNC_CFG_ENTRY(init_client)
FNC_CFG_ENTRY(bankrob)
FNC_CFG_ENTRY(briefing)
FNC_CFG_ENTRY(buyshop)
FNC_CFG_ENTRY(communications)
FNC_CFG_ENTRY(halo)
FNC_CFG_ENTRY(holster)
FNC_CFG_ENTRY(loop)
FNC_CFG_ENTRY(policehorn)
FNC_CFG_ENTRY(pullout)
FNC_CFG_ENTRY(siren)
FNC_CFG_ENTRY(smoke)
FNC_CFG_ENTRY(triggers)
FNC_CFG_CL_END()