#include "..\..\includes\base.h"
#define PREFIX main_menu
FNC_CFG_CL_START()
	FNC_CFG_ENTRY(init1)
	FNC_CFG_ENTRY(init2)
	FNC_CFG_ENTRY(create)
	FNC_CFG_ENTRY(handle_bank)
	FNC_CFG_ENTRY(handle_crimes)
	FNC_CFG_ENTRY(handle_economy)
	FNC_CFG_ENTRY(handle_elections)
	FNC_CFG_ENTRY(handle_factories)
	FNC_CFG_ENTRY(handle_finances)
	FNC_CFG_ENTRY(handle_gangs)
	FNC_CFG_ENTRY(handle_gang_areas)
	FNC_CFG_ENTRY(handle_legislation)
	FNC_CFG_ENTRY(handle_licenes)
	FNC_CFG_ENTRY(handle_players)
	FNC_CFG_ENTRY(handle_statistics)
	FNC_CFG_ENTRY(handle_workplaces)
	FNC_CFG_ENTRY(right_setup)
	FNC_CFG_ENTRY(setup)
FNC_CFG_CL_END()