#include "..\..\includes\base.h\"

FNC_CFG_ENTRY(init1)
FNC_CFG_ENTRY(init2)
FNC_CFG_ENTRY(action)
FNC_CFG_ENTRY(actions)
FNC_CFG_ENTRY(actions_remove)
FNC_CFG_ENTRY(add_new_action)
FNC_CFG_ENTRY(clear_new_actions)
FNC_CFG_ENTRY(actions_loop)
FNC_CFG_ENTRY(add_refuel_action)
FNC_CFG_ENTRY(check_actions)
FNC_CFG_ENTRY(get_nearest_station)
FNC_CFG_ENTRY(get_refuel_action)
FNC_CFG_ENTRY(get_refuel_vehicle)
FNC_CFG_ENTRY(get_refueling)
FNC_CFG_ENTRY(noscript)
FNC_CFG_ENTRY(refuel_tank)
FNC_CFG_ENTRY(remove_refuel_action)
FNC_CFG_ENTRY(set_refuel_action)
FNC_CFG_ENTRY(set_refueling)
