#define INV_INDEX_SHOP_LIST_ITEM 0
#define INV_INDEX_SHOP_LIST_STOCK 1
#define INV_INDEX_SHOP_LIST_STOCK_MAX 2

#define INV_INDEX_SHOP_OBJECT 0
#define INV_INDEX_SHOP_NAME 1
#define INV_INDEX_SHOP_CRATE 2
#define INV_INDEX_SHOP_LOGIC 3
#define INV_INDEX_SHOP_BUYLIST 4
#define INV_INDEX_SHOP_SELLLIST 5
#define INV_INDEX_SHOP_LICENSE 6

#define INV_INDEX_VENDOR_OBJECT 0
#define INV_INDEX_VENDOR_NAME 1

