#include "..\..\includes\base.h\"

FNC_CFG_ENTRY(init1)
FNC_CFG_ENTRY(init2)
FNC_CFG_ENTRY(createattachment)
FNC_CFG_ENTRY(createbisitem)
FNC_CFG_ENTRY(createfort)
FNC_CFG_ENTRY(createfort_init_handler)
FNC_CFG_ENTRY(createfort_init_handler_persistent)
FNC_CFG_ENTRY(creategoggles)
FNC_CFG_ENTRY(creategunboxlocal)
FNC_CFG_ENTRY(createheadgear)
FNC_CFG_ENTRY(createitem)
FNC_CFG_ENTRY(createlinkeditem)
FNC_CFG_ENTRY(createmag)
FNC_CFG_ENTRY(createpack)
FNC_CFG_ENTRY(createuniform)
FNC_CFG_ENTRY(createvest)
FNC_CFG_ENTRY(createweapon)
FNC_CFG_ENTRY(locateclosestvehicle)
FNC_CFG_ENTRY(vendor_data)
