#include "..\..\includes\base.h"
#define PREFIX stun
FNC_CFG_CL_START()
	FNC_CFG_ENTRY(init1)
	FNC_CFG_ENTRY(init2)
	FNC_CFG_ENTRY(agony)
	FNC_CFG_ENTRY(agony_recieve)
	FNC_CFG_ENTRY(annouce_hit)
	FNC_CFG_ENTRY(announce)
	FNC_CFG_ENTRY(blur_effect_wait)
	FNC_CFG_ENTRY(close_range)
	FNC_CFG_ENTRY(drop_weapons)
	FNC_CFG_ENTRY(effects_AI)
	FNC_CFG_ENTRY(effects_full)
	FNC_CFG_ENTRY(effects_light)
	FNC_CFG_ENTRY(gun_sound)
	FNC_CFG_ENTRY(gun_sound_receive)
	FNC_CFG_ENTRY(pistol)
	FNC_CFG_ENTRY(pistol_back)
	FNC_CFG_ENTRY(pistol_front)
	FNC_CFG_ENTRY(pistol_hit)
	FNC_CFG_ENTRY(shot_close)
	FNC_CFG_ENTRY(shot_far)
	FNC_CFG_ENTRY(using_weapon)
FNC_CFG_CL_END()