#include "..\..\includes\base.h"

FNC_CFG_ENTRY(init1)
FNC_CFG_ENTRY(init2)
FNC_CFG_ENTRY(add)
FNC_CFG_ENTRY(angle)
FNC_CFG_ENTRY(dotp)
FNC_CFG_ENTRY(drawModel)
FNC_CFG_ENTRY(interpolate)
FNC_CFG_ENTRY(magnitude)
FNC_CFG_ENTRY(matrixX)
FNC_CFG_ENTRY(normalize)
FNC_CFG_ENTRY(resize)
FNC_CFG_ENTRY(rotate3d)
FNC_CFG_ENTRY(subtract)
