#include "..\..\includes\base.h"
#define PREFIX jip
FNC_CFG_CL_START()
	FNC_CFG_ENTRY(init1)
	FNC_CFG_ENTRY(init2)
	FNC_CFG_ENTRY(cleanup)
	FNC_CFG_ENTRY(execute)
	FNC_CFG_ENTRY(get)
	FNC_CFG_ENTRY(get_request_receive)
	FNC_CFG_ENTRY(get_setup)
	FNC_CFG_ENTRY(load)
	FNC_CFG_ENTRY(message)
	FNC_CFG_ENTRY(register)
	FNC_CFG_ENTRY(register_request_receive)
	FNC_CFG_ENTRY(register_setup)
	FNC_CFG_ENTRY(set)
	FNC_CFG_ENTRY(setup)
	FNC_CFG_ENTRY(wait)
FNC_CFG_CL_END()