#define VEH_STR_INDEX_DATA_ID 0
#define VEH_STR_INDEX_DATA_CLASS 1
#define VEH_STR_INDEX_DATA_UID 2
#define VEH_STR_INDEX_ID 0
#define VEH_STR_INDEX_TITLE 1
#define VEH_STR_INDEX_DATA_KEYS 2
#define VEH_STR_INDEX_DATA_ENTRIES 3