#define DLLG_LOTTO_DATA_INDEX_ID 0
#define DLLG_LOTTO_DATA_INDEX_SHOP 1
#define DLLG_LOTTO_DATA_INDEX_TICKETS 2

#define DLLG_LOTTO_TICKET_INDEX_ID 0
#define DLLG_LOTTO_TICKET_INDEX_NAME 1
#define DLLG_LOTTO_TICKET_INDEX_PRICE 2
#define DLLG_LOTTO_TICKET_INDEX_PAYOUT 3
#define DLLG_LOTTO_TICKET_INDEX_CHANCE 4