#include "..\..\includes\base.h"
#define PREFIX lotto_menu
FNC_CFG_CL_START()
FNC_CFG_ENTRY(init_pre)
FNC_CFG_ENTRY(add_actions)
FNC_CFG_ENTRY(interact_lotto_play)
FNC_CFG_ENTRY(lookup_id)
FNC_CFG_ENTRY(menu_combo_blur)
FNC_CFG_ENTRY(menu_combo_focus)
FNC_CFG_ENTRY(menu_create)
FNC_CFG_ENTRY(menu_selection_changed)
FNC_CFG_ENTRY(menu_setup)
FNC_CFG_ENTRY(player_near)
FNC_CFG_ENTRY(remove_actions)
FNC_CFG_ENTRY(ticket_lookup_id)
FNC_CFG_CL_END()