#include "..\..\includes\base.h"
#define PREFIX invokeJava
FNC_CFG_CL_START()
FNC_CFG_ENTRY(getAllPlayerVariables)
FNC_CFG_ENTRY(getenv)
FNC_CFG_ENTRY(getPlayerVariable)
FNC_CFG_ENTRY(getPlayerVariableNameByIndex)
FNC_CFG_ENTRY(getPlayerVariablesCount)
FNC_CFG_ENTRY(method)
FNC_CFG_ENTRY(parseResult)
FNC_CFG_ENTRY(reloadPlayerVariables)
FNC_CFG_ENTRY(removePlayerVariable)
FNC_CFG_ENTRY(setLocation)
FNC_CFG_ENTRY(unloadPlayerVariables)
FNC_CFG_ENTRY(updatePlayerVariable)
FNC_CFG_ENTRY(wipeAllPlayerVariables)
FNC_CFG_ENTRY(wipePlayerVariables)
FNC_CFG_CL_END()