#include "../../includes/base.h"

FNC_CFG_ENTRY(init1)
FNC_CFG_ENTRY(init2)
FNC_CFG_ENTRY(getAllPlayerVariables)
FNC_CFG_ENTRY(getenv)
FNC_CFG_ENTRY(getPlayerVariable)
FNC_CFG_ENTRY(getPlayerVariableNameByIndex)
FNC_CFG_ENTRY(getPlayerVariablesCount)
FNC_CFG_ENTRY(logError)
FNC_CFG_ENTRY(logInfo)
FNC_CFG_ENTRY(logThis)
FNC_CFG_ENTRY(logThis_request_receive)
FNC_CFG_ENTRY(logThis_setup)
FNC_CFG_ENTRY(logWarning)
FNC_CFG_ENTRY(method)
FNC_CFG_ENTRY(parseResult)
FNC_CFG_ENTRY(persist)
FNC_CFG_ENTRY(reloadPlayerVariables)
FNC_CFG_ENTRY(removePlayerVariable)
FNC_CFG_ENTRY(setLocation)
FNC_CFG_ENTRY(unloadPlayerVariables)
FNC_CFG_ENTRY(updatePlayerVariable)
FNC_CFG_ENTRY(wipeAllPlayerVariables)
FNC_CFG_ENTRY(wipePlayerVariables)
