#include "..\..\includes\base.h"
#define PREFIX paint
FNC_CFG_CL_START()
	FNC_CFG_ENTRY(init1)
	FNC_CFG_ENTRY(init2)
	FNC_CFG_ENTRY(buy)
	FNC_CFG_ENTRY(dialog)
	FNC_CFG_ENTRY(dialog_full)
	FNC_CFG_ENTRY(dialog_setup)
	FNC_CFG_ENTRY(preview_camera)
	FNC_CFG_ENTRY(preview_zoom)
	FNC_CFG_ENTRY(r_buy)
	FNC_CFG_ENTRY(t_apply)
	FNC_CFG_ENTRY(t_r_all)
	FNC_CFG_ENTRY(t_r_slot)
FNC_CFG_CL_END()