#include "..\..\includes\base.h"
#define PREFIX bis_expected
FNC_CFG_CL_START()
	FNC_CFG_ENTRY(init1)
	FNC_CFG_ENTRY(init2)
	FNC_CFG_ENTRY(addItem2)
	FNC_CFG_ENTRY(addPlayerInventoryItem)
	FNC_CFG_ENTRY(addWeaponItem)
	FNC_CFG_ENTRY(realLoadUniform)
	FNC_CFG_ENTRY(realLoadVest)
	FNC_CFG_ENTRY(removeItemFromCargo)
	FNC_CFG_ENTRY(removeItemFromCargoGlobal)
	FNC_CFG_ENTRY(removeItemFromHandgun)
	FNC_CFG_ENTRY(removeItemFromSecondaryWeapon)
	FNC_CFG_ENTRY(removePlayerInventoryItem)
	FNC_CFG_ENTRY(removeWeaponItem)
	FNC_CFG_ENTRY(uniformSpaceFor)
	FNC_CFG_ENTRY(unitDelete)
	FNC_CFG_ENTRY(vestSpaceFor)
FNC_CFG_CL_END()