#include "..\..\includes\base.h\"

FNC_CFG_ENTRY(init1)
FNC_CFG_ENTRY(init2)
FNC_CFG_ENTRY(defuser)
FNC_CFG_ENTRY(drugs)
FNC_CFG_ENTRY(fishing)
FNC_CFG_ENTRY(food)
FNC_CFG_ENTRY(gaskmask)
FNC_CFG_ENTRY(handy)
FNC_CFG_ENTRY(initfilenames)
FNC_CFG_ENTRY(itembag)
FNC_CFG_ENTRY(largerepair)
FNC_CFG_ENTRY(lighter)
FNC_CFG_ENTRY(lockpick)
FNC_CFG_ENTRY(m_ammo)
FNC_CFG_ENTRY(m_ammo_add)
FNC_CFG_ENTRY(medkit)
FNC_CFG_ENTRY(nitro)
FNC_CFG_ENTRY(nouse)
FNC_CFG_ENTRY(repair)
FNC_CFG_ENTRY(stun_armor)
FNC_CFG_ENTRY(suicide_bomb)
FNC_CFG_ENTRY(supgrade)
FNC_CFG_ENTRY(syphon)
FNC_CFG_ENTRY(useresource)
FNC_CFG_ENTRY(vclammo)
FNC_CFG_ENTRY(weaponbag)
