#include "..\..\includes\base.h"
#define PREFIX wbl
FNC_CFG_CL_START()
	FNC_CFG_ENTRY(init1)
	FNC_CFG_ENTRY(init2)
	FNC_CFG_ENTRY(dialog_init)
	FNC_CFG_ENTRY(gettype_name)
	FNC_CFG_ENTRY(gettype_num)
	FNC_CFG_ENTRY(init_c)
	FNC_CFG_ENTRY(init_s)
	FNC_CFG_ENTRY(load_s)
	FNC_CFG_ENTRY(l_add)
	FNC_CFG_ENTRY(l_remove)
	FNC_CFG_ENTRY(l_remove_all)
	FNC_CFG_ENTRY(r)
	FNC_CFG_ENTRY(refresh_r)
	FNC_CFG_ENTRY(refresh_s)
	FNC_CFG_ENTRY(save)
FNC_CFG_CL_END()