#include "..\..\includes\base.h\"

FNC_CFG_ENTRY(init1)
FNC_CFG_ENTRY(init2)
FNC_CFG_ENTRY(actions)
FNC_CFG_ENTRY(adddirections)
FNC_CFG_ENTRY(addpositions)
FNC_CFG_ENTRY(buy)
FNC_CFG_ENTRY(closedoor)
FNC_CFG_ENTRY(getkey)
FNC_CFG_ENTRY(homelogic)
FNC_CFG_ENTRY(housewatch)
FNC_CFG_ENTRY(info)
FNC_CFG_ENTRY(isdooropening)
FNC_CFG_ENTRY(isforsale)
FNC_CFG_ENTRY(islocked)
FNC_CFG_ENTRY(isownerconnected)
FNC_CFG_ENTRY(lock)
FNC_CFG_ENTRY(main)
FNC_CFG_ENTRY(mykey)
FNC_CFG_ENTRY(opendoor)
FNC_CFG_ENTRY(sell)
FNC_CFG_ENTRY(setforsale)
FNC_CFG_ENTRY(setobject)
FNC_CFG_ENTRY(unlock)
FNC_CFG_ENTRY(updateactions)
