#define INDEX_AREA_NAME 0
#define INDEX_AREA_MARKER 1
#define INDEX_AREA_ANIMALS 2

#define INDEX_ANIMAL_NAME 0
#define INDEX_ANIMAL_CLASS 1
#define INDEX_ANIMAL_ITEM 2
#define INDEX_ANIMAL_MIN_COUNT 3
#define INDEX_ANIMAL_MAX_COUNT 4
#define INDEX_ANIMAL_SPAWN_RADIUS 5
#define INDEX_ANIMAL_SPAWN_RATE 6
#define INDEX_ANIMAL_DESPAWN_RADIUS 7