#include "..\..\includes\base.h"
#define PREFIX tree
FNC_CFG_CL_START()
	FNC_CFG_ENTRY(init1)
	FNC_CFG_ENTRY(init2)
	FNC_CFG_ENTRY(average_grade)
	FNC_CFG_ENTRY(create_item)
	FNC_CFG_ENTRY(dead)
	FNC_CFG_ENTRY(delete_object)
	FNC_CFG_ENTRY(get_object)
	FNC_CFG_ENTRY(hide)
	FNC_CFG_ENTRY(joined_sync)
	FNC_CFG_ENTRY(local_hide)
	FNC_CFG_ENTRY(near)
	FNC_CFG_ENTRY(register)
	FNC_CFG_ENTRY(register_request_receive)
	FNC_CFG_ENTRY(register_setup)
	FNC_CFG_ENTRY(set_dead)
	FNC_CFG_ENTRY(sort_by_distance)
FNC_CFG_CL_END()