#include "..\..\includes\base.h"
#define PREFIX drag
FNC_CFG_CL_START()
	FNC_CFG_ENTRY(init1)
	FNC_CFG_ENTRY(init2)
	FNC_CFG_ENTRY(add_action)
	FNC_CFG_ENTRY(attach_lookup_class)
	FNC_CFG_ENTRY(attach_lookup_class_selection)
	FNC_CFG_ENTRY(interact_object_put_vehicle)
	FNC_CFG_ENTRY(object_active)
	FNC_CFG_ENTRY(object_add_attach_actions)
	FNC_CFG_ENTRY(object_add_item_actions)
	FNC_CFG_ENTRY(object_attach)
	FNC_CFG_ENTRY(object_label)
	FNC_CFG_ENTRY(object_release)
	FNC_CFG_ENTRY(object_remove_attach_actions)
	FNC_CFG_ENTRY(object_weightless)
	FNC_CFG_ENTRY(put_inventory_avalable)
	FNC_CFG_ENTRY(put_vehicle_active)
	FNC_CFG_ENTRY(remote_attach)
	FNC_CFG_ENTRY(remote_detach)
	FNC_CFG_ENTRY(remove_action)
	FNC_CFG_ENTRY(take_object)
	FNC_CFG_ENTRY(take_object_available)
	FNC_CFG_ENTRY(target_vehicle)
FNC_CFG_CL_END()