#include "..\..\includes\base.h"
#define PREFIX underwater_base
FNC_CFG_CL_START()
	FNC_CFG_ENTRY(init1)
	FNC_CFG_ENTRY(init2)
	FNC_CFG_ENTRY(underground_base_player_inside)
	FNC_CFG_ENTRY(underwater_base_check_transition)
	FNC_CFG_ENTRY(underwater_base_player_inside)
	FNC_CFG_ENTRY(underwater_base_setup)
	FNC_CFG_ENTRY(underwater_setup_lights)
	FNC_CFG_ENTRY(under_base)
	FNC_CFG_ENTRY(under_base_check_effects)
	FNC_CFG_ENTRY(under_base_set_day)
	FNC_CFG_ENTRY(under_base_set_night)
FNC_CFG_CL_END()