#include "..\..\includes\base.h"
#define PREFIX halo
FNC_CFG_CL_START()
FNC_CFG_ENTRY(init1)
FNC_CFG_ENTRY(init2)
FNC_CFG_ENTRY(activate_smoke)
FNC_CFG_ENTRY(add_smoke_actions)
FNC_CFG_ENTRY(deactivate_smoke)
FNC_CFG_ENTRY(jump)
FNC_CFG_ENTRY(jump_add_actions)
FNC_CFG_ENTRY(jump_allowed)
FNC_CFG_ENTRY(open_parachute)
FNC_CFG_ENTRY(remove_all_smoke_actions)
FNC_CFG_ENTRY(remove_smoke_action)
FNC_CFG_ENTRY(start)
FNC_CFG_CL_END()