#include "../../includes/base.h"

FNC_CFG_ENTRY(init1)
FNC_CFG_ENTRY(init2)
FNC_CFG_ENTRY(calculate_half_waypoint)
FNC_CFG_ENTRY(create_marker)
FNC_CFG_ENTRY(create_truck)
FNC_CFG_ENTRY(create_units)
FNC_CFG_ENTRY(debug)
FNC_CFG_ENTRY(get_current_state)
FNC_CFG_ENTRY(get_spawn)
FNC_CFG_ENTRY(get_state)
FNC_CFG_ENTRY(init_handler_persistent)
FNC_CFG_ENTRY(loop)
FNC_CFG_ENTRY(mission_check_complete)
FNC_CFG_ENTRY(mission_check_damage)
FNC_CFG_ENTRY(mission_check_position)
FNC_CFG_ENTRY(mission_check_state)
FNC_CFG_ENTRY(mission_check_targets)
FNC_CFG_ENTRY(mission_iteration)
FNC_CFG_ENTRY(mission_loop)
FNC_CFG_ENTRY(set_state)
FNC_CFG_ENTRY(side2string)
FNC_CFG_ENTRY(side_msg)
FNC_CFG_ENTRY(state2str)
FNC_CFG_ENTRY(units_exit)
