#include "..\..\includes\base.h"
#define PREFIX server
FNC_CFG_CL_START()
FNC_CFG_ENTRY(init)
FNC_CFG_ENTRY(delete_group)
FNC_CFG_ENTRY(druguse)
FNC_CFG_ENTRY(drug_replenish_init)
FNC_CFG_ENTRY(drug_replenish)
FNC_CFG_ENTRY(druguse_init)
FNC_CFG_ENTRY(get_array)
FNC_CFG_ENTRY(group_loop_init)
FNC_CFG_ENTRY(group_loop)
FNC_CFG_ENTRY(robpool_init)
FNC_CFG_ENTRY(robpool)
FNC_CFG_ENTRY(setup_vendors)
FNC_CFG_ENTRY(set_array)
FNC_CFG_ENTRY(set_array_checked)
FNC_CFG_ENTRY(shop_drug_replenish)
FNC_CFG_ENTRY(stationrob_init)
FNC_CFG_ENTRY(stationrob_loop)
FNC_CFG_CL_END()