#include "..\..\includes\base.h"

FNC_CFG_ENTRY(init1)
FNC_CFG_ENTRY(init2)
FNC_CFG_ENTRY(delete_group)
FNC_CFG_ENTRY(druguse)
FNC_CFG_ENTRY(drug_replenish)
FNC_CFG_ENTRY(drug_replenish_loop)
FNC_CFG_ENTRY(get_array)
FNC_CFG_ENTRY(loop)
FNC_CFG_ENTRY(robpool)
FNC_CFG_ENTRY(setup_vendors)
FNC_CFG_ENTRY(set_array)
FNC_CFG_ENTRY(set_array_checked)
FNC_CFG_ENTRY(shop_drug_replenish)
FNC_CFG_ENTRY(stationrobloop)
