#include "..\..\includes\base.h"

FNC_CFG_ENTRY(init1)
FNC_CFG_ENTRY(init2)
FNC_CFG_ENTRY(add_actions)
FNC_CFG_ENTRY(cleanup_walls)
FNC_CFG_ENTRY(create)
FNC_CFG_ENTRY(create_entrance)
FNC_CFG_ENTRY(create_underground)
FNC_CFG_ENTRY(door_sound)
FNC_CFG_ENTRY(door_sound_handler)
FNC_CFG_ENTRY(enter)
FNC_CFG_ENTRY(exit)
FNC_CFG_ENTRY(match_doors)
FNC_CFG_ENTRY(player_looking)
FNC_CFG_ENTRY(player_near)
FNC_CFG_ENTRY(remove_actions)
FNC_CFG_ENTRY(traverse_door)
FNC_CFG_ENTRY(underground_base_check_animation)
