#define GANG_INDEX_ID 0
#define GANG_INDEX_NAME 1
#define GANG_INDEX_MEMBERS 2
#define GANG_INDEX_OPEN 3
#define GANG_INDEX_GROUP 4

#define GANG_AREA_INDEX_TEXT 0
#define GANG_AREA_INDEX_CODE 1
#define GANG_AREA_INDEX_COND 2