#define INDEX_LOADOUT_CLASS 0
#define INDEX_LOADOUT_VARIANTS 1
#define INDEX_LOADOUT_VARIANT_ID 0
#define INDEX_LOADOUT_VARIANT_MODS 1
#define INDEX_LOADOUT_VARIANT_MOD_METHOD 0
#define INDEX_LOADOUT_VARIANT_MOD_ARGUMENTS 1
#define INDEX_LOADOUT_VARIANT_MOD_REPEAT 2

#define INDEX_TEXTURE_CLASS 0
#define INDEX_TEXTURE_VARIANTS 1
#define INDEX_TEXTURE_VARIANT_ID 0
#define INDEX_TEXTURE_VARIANT_SELECTIONS 1
#define INDEX_TEXTURE_VARIANT_SELECTION_INDEX 0
#define INDEX_TEXTURE_VARIANT_SELECTION_PATH 1

#define INDEX_ANIMATION_CLASS 0
#define INDEX_ANIMATION_VARIANTS 1
#define INDEX_ANIMATION_VARIANT_ID 0
#define INDEX_ANIMATION_VARIANT_ANIMATIONS 1
#define INDEX_ANIMATION_VARIANT_ANIMATION_NAME 0
#define INDEX_ANIMATION_VARIANT_ANIMATION_STATE 1

#define INDEX_GEAR_CARGO_WEAPONS 0
#define INDEX_GEAR_CARGO_MAGAZINES 1