#include "..\..\includes\base.h"
#define PREFIX nametags
FNC_CFG_CL_START()
	FNC_CFG_ENTRY(init1)
	FNC_CFG_ENTRY(init2)
	FNC_CFG_ENTRY(3d_tags_draw)
	FNC_CFG_ENTRY(loading_check_stance)
	FNC_CFG_ENTRY(tags_control)
	FNC_CFG_ENTRY(tags_draw)
	FNC_CFG_ENTRY(tags_driver_string)
	FNC_CFG_ENTRY(tags_head_position)
	FNC_CFG_ENTRY(tags_loop)
	FNC_CFG_ENTRY(tags_max_z)
	FNC_CFG_ENTRY(tags_position)
	FNC_CFG_ENTRY(tags_vehicle)
	FNC_CFG_ENTRY(water_edge_check_effects)
FNC_CFG_CL_END()