#define INDEX_CLASS 0
#define INDEX_TOWING_HITCH_OFFSET 1
#define INDEX_TOWED_HITCH_OFFSET 2
#define INDEX_TOWED_FRONT_AXLE 3
#define INDEX_TOWED_BACK_AXLE 4
#define INDEX_TOWING_ENABLED 5
#define INDEX_TOWED_ENABLED 6