#include "..\..\includes\base.h"
#define PREFIX plant
FNC_CFG_CL_START()
FNC_CFG_ENTRY(init_pre)
FNC_CFG_ENTRY(add_actions)
FNC_CFG_ENTRY(get_count)
FNC_CFG_ENTRY(harvest_yield)
FNC_CFG_ENTRY(interact_plant_seedling)
FNC_CFG_ENTRY(life_loop)
FNC_CFG_ENTRY(player_near)
FNC_CFG_ENTRY(remove_actions)
FNC_CFG_ENTRY(seed_handler_persistent)
FNC_CFG_ENTRY(seed_lookup_id)
FNC_CFG_ENTRY(update_count)
FNC_CFG_ENTRY(update_yield)
FNC_CFG_CL_END()