#include "..\..\includes\base.h"

FNC_CFG_ENTRY(init1)
FNC_CFG_ENTRY(init2)
FNC_CFG_ENTRY(bash)
FNC_CFG_ENTRY(Bomb_Vehicle)
FNC_CFG_ENTRY(buildings_list)
FNC_CFG_ENTRY(buildings_protect)
FNC_CFG_ENTRY(DialogAllPlayersList)
FNC_CFG_ENTRY(DialogCivilianPlayersList)
FNC_CFG_ENTRY(DialogNotCopsList)
FNC_CFG_ENTRY(DialogPlayerList)
FNC_CFG_ENTRY(format_integer)
FNC_CFG_ENTRY(generic_config_text)
FNC_CFG_ENTRY(generic_display_name)
FNC_CFG_ENTRY(generic_icon_path)
FNC_CFG_ENTRY(generic_picture_path)
FNC_CFG_ENTRY(Isse_AddCrimeLogEntry)
FNC_CFG_ENTRY(parse_number)
FNC_CFG_ENTRY(SayDirectSpeach)
FNC_CFG_ENTRY(setPitchBank)
FNC_CFG_ENTRY(strlen)
FNC_CFG_ENTRY(strstr)
FNC_CFG_ENTRY(substr)
FNC_CFG_ENTRY(toLowerArray)
