#include "..\..\includes\base.h"

FNC_CFG_ENTRY(init1)
FNC_CFG_ENTRY(init2)
FNC_CFG_ENTRY(player_swap_weapon_items)
FNC_CFG_ENTRY(attachments_base)
FNC_CFG_ENTRY(compatible_attachments)
FNC_CFG_ENTRY(compatible_muzzle)
FNC_CFG_ENTRY(compatible_side_rail)
FNC_CFG_ENTRY(compatible_slot_attachments)
FNC_CFG_ENTRY(compatible_top_rail)
FNC_CFG_ENTRY(compatible_with_attachment)
FNC_CFG_ENTRY(display_name)
FNC_CFG_ENTRY(modifications_dialog_setup)
FNC_CFG_ENTRY(picture_path)
FNC_CFG_ENTRY(slot_label_changed)
