#include "..\..\includes\base.h"
#define PREFIX eh
FNC_CFG_CL_START()
FNC_CFG_ENTRY(init_pre)
FNC_CFG_ENTRY(player_connected)
FNC_CFG_ENTRY(player_disconnected)
FNC_CFG_ENTRY(fired)
FNC_CFG_ENTRY(firednear)
FNC_CFG_ENTRY(fired_mortar)
FNC_CFG_ENTRY(fired_vehicle)
FNC_CFG_ENTRY(getin_mortar)
FNC_CFG_ENTRY(handledamage)
FNC_CFG_ENTRY(hitpart)
FNC_CFG_ENTRY(weaponassembled)
FNC_CFG_CL_END()