#include "..\..\includes\base.h"
#define PREFIX camera_menu
FNC_CFG_CL_START()
FNC_CFG_ENTRY(action)
FNC_CFG_ENTRY(actions_list)
FNC_CFG_ENTRY(activate_command)
FNC_CFG_ENTRY(clipboard_objectFromNetId)
FNC_CFG_ENTRY(combo_blur)
FNC_CFG_ENTRY(combo_focus)
FNC_CFG_ENTRY(create)
FNC_CFG_ENTRY(input_text)
FNC_CFG_ENTRY(modify_heading)
FNC_CFG_ENTRY(modify_offset)
FNC_CFG_ENTRY(selected_object)
FNC_CFG_ENTRY(setup)
FNC_CFG_ENTRY(set_offset_heading)
FNC_CFG_CL_END()