#include "..\..\includes\base.h"
#define PREFIX bombs
FNC_CFG_CL_START()
	FNC_CFG_ENTRY(init1)
	FNC_CFG_ENTRY(init2)
	FNC_CFG_ENTRY(add)
	FNC_CFG_ENTRY(bombs)
	FNC_CFG_ENTRY(client)
	FNC_CFG_ENTRY(config)
	FNC_CFG_ENTRY(delete)
	FNC_CFG_ENTRY(edit)
	FNC_CFG_ENTRY(idexists)
	FNC_CFG_ENTRY(plant)
	FNC_CFG_ENTRY(server)
	FNC_CFG_ENTRY(spawn)
	FNC_CFG_ENTRY(use)
FNC_CFG_CL_END()